using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CodingBat
{
    class Program
    {
        static void Main(string[] args)
        {
            //Console.WriteLine(Recursion.Factorial(5));
            //Console.ReadLine();
            //Console.WriteLine(Recursion.BunnyEars(100));
            //Console.ReadLine();
            //Console.WriteLine(Recursion.Fibonacci(6));
            //Console.ReadLine();
            //Console.WriteLine(Recursion.BunnyEars2(2));
            //Console.WriteLine(Recursion.Triangle(4));
            //Console.WriteLine(Recursion.SumDigits(1004490));
            //Console.WriteLine(Recursion.Count7(70777));
            //Console.WriteLine(Recursion.CountPairs("aaafghgk"));
            //Console.WriteLine(Recursion.CountABC("abax0abcxaba"));
            //Console.WriteLine(Recursion.Count11("111"));
            //Console.WriteLine(Recursion.CleanString("Hello"));
            //Console.WriteLine(Recursion.CountHi2("xhixhi"));
            //Console.WriteLine(Recursion.StringDistribution("cccatcowcatxx", "cat"));
            //Console.WriteLine( Warmup1.SleepIn(false, true) ); 
            //Console.WriteLine(Warmup1.MonkeyTrouble(false,false));
            //Console.WriteLine(Warmup1.SumDouble(999999999, 999999999));
            //Console.WriteLine(Warmup1.Diff21(21));
            //Console.WriteLine(Warmup1.ParrotTrouble(false, 4));
            //Console.WriteLine(Warmup1.Makes10(1, 9));
            //Console.WriteLine(Warmup1.NearHundred(89));
            //Console.WriteLine(Warmup1.PosNeg(-1, -1, false));
            //Console.WriteLine(Warmup1.NotString("x"));
            //Console.WriteLine(Warmup1.MissingChar("kitten", 4));
            //Console.WriteLine(Warmup1.FrontBack("a"));
            //Console.WriteLine(Warmup1.Front3("ab"));
            //Console.WriteLine(Warmup1.BackAround("a"));
            //Console.WriteLine(Warmup1.Or35(10));
            //Console.WriteLine(Warmup1.Front22("kitten"));
            //Console.WriteLine(Warmup1.StartHi("hello hi"));
            //Console.WriteLine(Warmup1.IcyHot(-1,110));
            //Console.WriteLine(Warmup1.In1020(11,11));
            //Console.WriteLine(Warmup1.HasTen(1, 12, 30));
            //Console.WriteLine(Warmup1.IOneTeen(20, 18));
            //Console.WriteLine(Warmup1.DelDel("adedbc"));
            //Console.WriteLine(Warmup1.MixStart("piz snacks"));
            //Console.WriteLine(Warmup1.StartOz("oxx"));
            //Console.WriteLine(Warmup1.intMax(1, 2, 3));
            //Console.WriteLine(Warmup1.Close10(13, 7));
            //Console.WriteLine(Warmup1.In3050(41, 49));
            //Console.WriteLine(Warmup1.Max1020(39, 131));
            //Console.WriteLine(Warmup1.StringE("Heelele"));
            //Console.WriteLine(Warmup1.LastDigit(113, 3));
            //Console.WriteLine(Warmup1.EndUp("Hello"));
            //Console.WriteLine(Warmup1.EveryNth("abcdefg", 3));
            //Console.WriteLine(WarmUp2.StringTimes("Hi", 1));
            //Console.WriteLine(WarmUp2.FrontTimes("Abc", 3));
            //Console.WriteLine(WarmUp2.CountXX("xxxx"));
            //Console.WriteLine(WarmUp2.DoubleX("xxxxx"));
            //Console.WriteLine(WarmUp2.StringBits("Heeololeo"));
            //Console.WriteLine(WarmUp2.StringSplosion("ab"));
            //Console.WriteLine(WarmUp2.Last2("hlaaalaalaolaa"));
            //Console.WriteLine(WarmUp2.ArrayCount9(new int[] { 9, 9, 9 }));
            //Console.WriteLine(WarmUp2.ArrayFront9(new int[] { 1, 9, 3/*, 9, 5, 6, 7, 8, 9*/ }));
            //Console.WriteLine(WarmUp2.Array123(new int[] { 1, 3, 1, 6, 7, 2, 94, 3, 2342, 554 }));
            //Console.WriteLine(WarmUp2.StringMatch("abccaasdasdssa", "axccfrdewsd"));
            //Console.WriteLine(WarmUp2.StringX("xabxxxcdx"));
            //Console.WriteLine(WarmUp2.AltPairs("kitten"));
            //Console.WriteLine(WarmUp2.StringYak("yxk123ya"));
            //Console.WriteLine(WarmUp2.Array667(new int[] { 0, 1, 3, 4, 5, 6, 6, 6 }));
            //Console.WriteLine(WarmUp2.NoTriples(new int[] { 1, 1, 1, 2, 2, 2, 1 }));
            //Console.WriteLine(WarmUp2.Has271(new int[] { 7, 12, 4 }));
            //Console.WriteLine(String1.HelloName("Bob"));
            //Console.WriteLine(String1.MAkeAbba("Yo", "Alice"));
            //Console.WriteLine(String1.MakeTags("cite", "Yay"));
            //Console.WriteLine(String1.MakeOutWord("[[]]", "word"));
            //Console.WriteLine(String1.ExtraEnd("ab"));
            //Console.WriteLine(String1.FirstTwo("ab"));
            //Console.WriteLine(String1.FirstHalf("HelloThere"));
            //Console.WriteLine(String1.WithoutEnd("coding"));
            //Console.WriteLine(String1.ComboString("aaa", "b"));
            //Console.WriteLine(String1.NonStart("java", "code"));
            //Console.WriteLine(String1.Left2("Hi"));
            //Console.WriteLine(String1.Right2("java"));
            //Console.WriteLine(String1.TheEnd("h", true));
            //Console.WriteLine(String1.WithoutEnd2("a"));
            //Console.WriteLine(String1.MiddleTwo("Practice"));
            //Console.WriteLine(String1.EndsLy("oddy"));
            //Console.WriteLine(String1.NTwice("Chocolate", 1));
            //Console.WriteLine(String1.TwoChar("java", 3));
            //Console.WriteLine(String1.MiddleThree("solving"));
            //Console.WriteLine(String1.HasBad("xxbadxx"));
            //Console.WriteLine(String1.AtFirst("hello"));
            //Console.WriteLine(String1.LastChars("", ""));
            //Console.WriteLine(String1.Concat("abc", ""));
            //Console.WriteLine(String1.LastTwo("ab"));
            //Console.WriteLine(String1.SeeColors("blueTimes"));
            //Console.WriteLine(String1.FrontAgain("ed"));
            //Console.WriteLine(String1.MinCat("Orange", "Apple"));
            //Console.WriteLine(String1.ExtraFront(""));
            //Console.WriteLine(String1.Without2("Hi"));
            //Console.WriteLine(String1.DeFront("a"));
            //Console.WriteLine(String1.StartWord("hippo", "i"));
            //Console.WriteLine(String1.WithoutX("Hxix"));
            //Console.WriteLine(String1.WithoutX2("Hi"));
            //Console.WriteLine(Array1.FirstLast6(new int[] { 6, 6, 7 }));
            //Console.WriteLine(Array1.SameFirstLast(new int[0]));
            //Console.WriteLine(Array1.MakePi());
            //Console.WriteLine(Array1.CommonEnd(new int[] { 1, 2, 3, 4, 5 }, new int[] { 2, 5 }));
            //Console.WriteLine(Array1.Sum3(new int[] { 3, 3, 3 }));
            //Console.WriteLine(Array1.RotateLeft3(new int[] { 1, 3, 77 }));
            //Console.WriteLine(Array1.Reverse3(new int[] { 1, 3, 77 }));
            //Console.WriteLine(Array1.MaxEnd3(new int[] { 1, 3, 77 }));
            //Console.WriteLine(Array1.Sum2(new int[] { 66, 6, 77 }));
            //Console.WriteLine(Array1.Has23(new int[] { 4,5}));
            //Console.WriteLine(Array1.No23(new int[] { 3, 5 }));
            //Console.WriteLine(Array1.MakeLast(new int[] { 3, 6, 7, 44, 43 }));
            //Console.WriteLine(Array1.Double23(new int[] { 3 }));
            //Console.WriteLine(Array1.Fix23(new int[] { 2, 3, 3 }));
            //Console.WriteLine(Array1.Start1(new int[] { 0 }, new int[0]));
            //Console.WriteLine(Array1.BiggerTwo(new int[] { 2, 4 }, new int[] { 3, 3 }));
            //Console.WriteLine(Array1.MakeMiddle(new int[] { 1, 2 }));
            //Console.WriteLine(Array1.PlusTwo(new int[] { 2, 4 }, new int[] { 3, 3 }));
            //Console.WriteLine(Array1.SwapEnds(new int[] { 8, 6, 7, 9, 5 }));
            //Console.WriteLine(Array1.MidThree(new int[] { 1, 2, 3 }));
            //Console.WriteLine(Array1.MaxTriple(new int[] { 35, 2, 3, 16, 7, 44, 13 }));
            //Console.WriteLine(Array1.FrontPiece(new int[] { 1, 2, 3 }));
            //Console.WriteLine(Array1.Unlucky1(new int[] { 1, 1, 1 }));
            //Console.WriteLine(Array1.Make2(new int[] { 4, 4 }, new int[0]));
            //Console.WriteLine(Array1.Front11(new int[] { 1, 7 }, new int[0]));
            //Console.WriteLine(Logic1.CigarParty(70, true));
            //Console.WriteLine(Logic1.DateFashion(5,6));
            //Console.WriteLine(Logic1.SquirrelPlay(95, true));
            //Console.WriteLine(Logic1.CaughtSpeeding(81, true));
            //Console.WriteLine(Logic1.SortaSum(10, 11));
            //Console.WriteLine(Logic1.AlarmClock(6,true));
            //Console.WriteLine(Logic1.Love6(-5, -1));
            //Console.WriteLine(Logic1.In1To10(11, true));
            //Console.WriteLine(Logic1.SpecialEleven(24));
            //Console.WriteLine(Logic1.More20(22));
            //Console.WriteLine(Logic1.Old35(15));
            //Console.WriteLine(Logic1.Less20(20));
            //Console.WriteLine(Logic1.NearTen(17));
            //Console.WriteLine(Logic1.TeenSum(132, 22));
            //Console.WriteLine(Logic1.AnswerCell(true, true, true));
            //Console.WriteLine(Logic1.TeaParty(20, 8));
            //Console.WriteLine(Logic1.FizzString("fib"));
            //Console.WriteLine(Logic1.FizzString2(75));
            //Console.WriteLine(Logic1.TwoAsOne(2,2,2));
            //Console.WriteLine(Logic1.InOrder(1, 1, 2, true));
            //Console.WriteLine(Logic1.InOrderEqual(5, 5, 7, true));
            //Console.WriteLine(Logic1.LastDigit(24, 14, 3));
            //Console.WriteLine(Logic1.WithoutDoubles(6, 6, true));
            //Console.WriteLine(Logic1.MaxMod5(15, 25));
            //Console.WriteLine(Logic1.RedTicket(0, 0, 0));
            //Console.WriteLine(Logic1.GreenTicket(2,3,2));
            //Console.WriteLine(Logic1.BlueTicket(20, 20, 10));
            //Console.WriteLine(Logic1.ShareDigit(32, 46));
            //Console.WriteLine(Logic1.SumLimit(8, 1));
            //Console.WriteLine(Logic2.MakeBricks(3, 2, 10));
            //Console.WriteLine(Logic2.LoneSum(3, 3, 3));
            //Console.WriteLine(Logic2.LuckySum(3, 10, 1));
            //Console.WriteLine(Logic2.NoTeenSum(2, 5, 15));
            //Console.WriteLine(Logic2.RoundSum(6, 4, 4));
            //Console.WriteLine(Logic2.CloseFar(4, 5, 3));
            //Console.WriteLine(String2.DoubleChar("Hi-There"));
            //Console.WriteLine(String2.CountHi("hiho not HOHIhi"));
            //Console.WriteLine(String2.CountCode("coAcodeBcoleccoreDD"));
            //Console.WriteLine(String2.EndOther("abcC", "abXabc"));
            //Console.WriteLine(String2.XYZThere("123abcbcdbabxyz"));
            //Console.WriteLine(String2.BobThere("abcbob"));
            //Console.WriteLine(String2.XYBalanced("12xabxxydxyxyzz"));
            //Console.WriteLine(String2.MixString("Long", "So"));
            //Console.WriteLine(String2.RepeatEnd("1234", 3));
            //Console.WriteLine(String2.RepeatFront("Java", 4));
            //Console.WriteLine(String2.RepeatSeparator("AAA", "", 0));
            //Console.WriteLine(String2.PrefixAgain("abXYabc", 3));
            //Console.WriteLine(String2.XYZMiddle("AxyzBBB"));
            //Console.WriteLine(String2.GetSandwich("xzy"));
            //Console.WriteLine(String2.SameStarChar("*xa*bz"));
            //Console.WriteLine(String2.OneTwo("1234567890"));
            //Console.WriteLine(String2.ZipZap("abcppp"));
            //Console.WriteLine(String2.StarOut("a"));
            //Console.WriteLine(String2.PlusOut("aaxxxxbb", "xx"));
            //Console.WriteLine(String2.WordEnds("XY1XY", "XY"));
            //Console.WriteLine(String3.CountYZ("zxyx"));
            //Console.WriteLine(String3.WithoutString("xxx", "xx"));
            //Console.WriteLine(String3.EqualIsNot("This is not"));
            //Console.WriteLine(String3.GHappy("ggxg"));
            //Console.WriteLine(String3.CountTriple("a"));
            //Console.WriteLine(String3.SumDigits("Chocolate"));
            //Console.WriteLine(String3.SameEnds("abcb"));
            //Console.WriteLine(String3.MirrorEnds("abXYZba"));
            //Console.WriteLine(String3.MaxBlock("XXBBBBbbxx"));
            //Console.WriteLine(String3.SumNumbers("aa11b33"));
            //Console.WriteLine(String3.NotReplace("This is right"));
            //Console.WriteLine(Array2.CountEvens(new int[] { 1, 3, 5 }));
            //Console.WriteLine(Array2.BigDiff(new int[] { 2, 10 }));
            //Console.WriteLine(Array2.CenterAverage(new int[] { 1, 2, 3, 4, 100 }));
            //Console.WriteLine(Array2.Sum13(new int[] { 1, 2, 2, 1, 13 }));
            //Console.WriteLine(Array2.Sum67(new int[] { 1, 1, 6, 7, 2 }));
            //Console.WriteLine(Array2.Has22(new int[] { 1, 2, 1, 2 }));
            //Console.WriteLine(Array2.Post4(new int[] { 2, 4, 1, 2 }));
            //Console.WriteLine(Array2.WithoutTenSameCopy(new int[] { 15, 0, 13, 10, 14 }));
            //Console.WriteLine(Array3.MaxSpan(new int[] { 1, 4, 2, 1, 4, 4, 4 }));
            //Console.WriteLine(Array3.Fix45(new int[] { 5, 4, 9, 4, 9, 5 }));
            //Console.WriteLine(Array3.SquareUp(3));
            //Console.WriteLine(Array3.SeriesUp(3));
            //Console.WriteLine(Array3.MaxMirror(new int[] { 21, 22, 9, 8, 7, 6, 23, 24, 6, 7, 8, 9, 25, 7, 8, 9 }));
            //Console.WriteLine(Array3.CountClumps(new int[] { 1, 1, 1, 1, 1 }));
            //Console.WriteLine(Recursion2.GroupSumClump(0, new int[] { 2, 4, 4, 8 }, 14));
            //Console.WriteLine(Recursion2.Split53(new int[] { 3, 5, 6, 10, 3, 3 }));
            //Console.WriteLine(AP1.CommonTwo(new string[] { "a", "a", "b", "b", "c" }, new string[] { "a", "b", "b", "b", "c" }));
            //Map1.Topping1(new Dictionary<string, string> { { "bread", "dirt" }, { "ice cream", "strawberries" } });
            //Map2.AllSwap(new string[] { "ax", "bx", "cx", "cy", "by", "ay", "aaa", "azz" });
            //Console.WriteLine(Functional1.NoX(new List<string>() { "the", "xxtxaxixxx" }));
            Functional2.Squared56(new List<int>() { 2 });
            Console.ReadLine();
        }
    }
}
